backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  site_domain: datsartcms.netlify.app
  site_id: 7cc4f3db-2b6b-4598-8e60-edf09fa87ba9
  # This will save to GitHub directly, triggering Vercel (not Netlify) builds

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Gallery" # Used in the UI
    folder: "_data/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string", default: "Digital Art" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "featured" # Used in routes, e.g., /admin/collections/featured
    label: "Featured Art" # Used in the UI
    folder: "_data/featured" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Art Type", name: "art_type", widget: "string", default: "Digital Art" }
      - { label: "Resolution", name: "resolution", widget: "string", default: "4K Resolution" }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Available", name: "available", widget: "boolean", default: true }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "Dat's Art" }
          - { label: "Site Subtitle", name: "site_subtitle", widget: "string", default: "Bringing Technology into Art" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Instagram Handle", name: "instagram_handle", widget: "string" }
          - { label: "WhatsApp Number", name: "whatsapp_number", widget: "string" }